name: Deploy main web
on:
  push:
    branches:
    - main

jobs:
  deploy_job:
    name: Deploy Job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch with submodules
      uses: actions/checkout@v4
      with:
        submodules: 'true'
        fetch-depth: '0'
    - name: Change the version of Service Worker
      run: |
        sed -i "s/const\sversion\s=\s.*;/const version = '$GITHUB_RUN_ID';/g" static/sw.js
        head static/sw.js
    - name: Install Hugo
      env:
        HUGO_VERSION: 0.125.2
      run: |
        mkdir -p download
        cd download
        wget -q "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz"
        tar -xvf *
        sudo cp hugo /usr/local/bin
        cd ..
    - name: Build the page with Hugo
      run: hugo --enableGitInfo --minify
    - name: Record the build variables
      run: |
        {
          echo "<p>"
          date
          echo -e "</p>\n<p>"
          hugo version
          echo -e "</p>\n<p>"
          uname -a
          echo -e "</p>\n<p>"
          echo "$GITHUB_SHA"
          echo -e "</p>\n<p>"
          echo "$GITHUB_RUN_ID"
          echo -e "</p>\n<p>"
          echo "$GITHUB_RUN_NUMBER"
          echo "</p> :)"
        } > public/stav.html 2>&1
    - name: Check and fix the version of bundle assets
      run: |
        sed -i "s='/css/style.*,='/css/$(basename public/css/style*)',=g" public/sw.js
        sed -i "s='/js/bundle.*,='/js/$(basename public/js/bundle*)',=g" public/sw.js
    - name: Do brotli compression
      run: |
        brotli -V
        for x in `/usr/bin/find public -type f -name '*.html' -o -name '*.css' -o -name '*.js'`; do
        	brotli --force --output=${x}.br ${x};
        done
    - name: SSH setup
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} #private SSH key
        KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }} #output of ssh-keyscan -p PORT -H some.domain.com some_IP
      run: |
        mkdir -p ~/.ssh
        echo "${KNOWN_HOSTS}" >> ~/.ssh/known_hosts
        echo "${DEPLOY_KEY}" > ~/.ssh/my_rsync_key
        {
          echo "HostKeyAlgorithms ssh-ed25519-cert-v01@openssh.com,ssh-ed25519"
          echo "KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org"
          echo "Ciphers chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com"
          echo "MACs umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com"
          echo "IPQoS throughput"
          echo "IdentityFile ~/.ssh/my_rsync_key"
        } >> ~/.ssh/config
        chmod -R 700 ~/.ssh
    - name: Deploy the page with Rsync
      env:
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
        LOCAL_PATH: 'public/'
        REMOTE_PATH: '~/zwieratko.sk/web/'
      run: |
        rsync -azrhv --stats --delete -e "ssh -T -x -v -p ${DEPLOY_PORT}" "${LOCAL_PATH}" "${DEPLOY_USER}@${DEPLOY_HOST}:${REMOTE_PATH}"
